try {
  throw new Error("Deu um problema no c√≥digo");
} catch (e) {
  console.log(e.name + ": " + e.message);
}
